/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthedWeeklyMenuRouteImport } from './routes/_authed/weekly-menu'
import { Route as AuthedImportRouteImport } from './routes/_authed/import'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AuthedRecipesRecipeIdRouteImport } from './routes/_authed/recipes/$recipeId'
import { Route as AuthedAdminVectorsRouteImport } from './routes/_authed/admin/vectors'
import { Route as AuthedAdminTagsRouteImport } from './routes/_authed/admin/tags'
import { Route as AuthedRecipesEditRecipeIdRouteImport } from './routes/_authed/recipes/edit/$recipeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWeeklyMenuRoute = AuthedWeeklyMenuRouteImport.update({
  id: '/weekly-menu',
  path: '/weekly-menu',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportRoute = AuthedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecipesRecipeIdRoute = AuthedRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminVectorsRoute = AuthedAdminVectorsRouteImport.update({
  id: '/admin/vectors',
  path: '/admin/vectors',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminTagsRoute = AuthedAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesEditRecipeIdRoute =
  AuthedRecipesEditRecipeIdRouteImport.update({
    id: '/recipes/edit/$recipeId',
    path: '/recipes/edit/$recipeId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/import': typeof AuthedImportRoute
  '/weekly-menu': typeof AuthedWeeklyMenuRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/tags': typeof AuthedAdminTagsRoute
  '/admin/vectors': typeof AuthedAdminVectorsRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/recipes/edit/$recipeId': typeof AuthedRecipesEditRecipeIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/import': typeof AuthedImportRoute
  '/weekly-menu': typeof AuthedWeeklyMenuRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthedIndexRoute
  '/admin/tags': typeof AuthedAdminTagsRoute
  '/admin/vectors': typeof AuthedAdminVectorsRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/recipes/edit/$recipeId': typeof AuthedRecipesEditRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/import': typeof AuthedImportRoute
  '/_authed/weekly-menu': typeof AuthedWeeklyMenuRoute
  '/api/chat': typeof ApiChatRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/tags': typeof AuthedAdminTagsRoute
  '/_authed/admin/vectors': typeof AuthedAdminVectorsRoute
  '/_authed/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/_authed/recipes/edit/$recipeId': typeof AuthedRecipesEditRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/import'
    | '/weekly-menu'
    | '/api/chat'
    | '/admin/tags'
    | '/admin/vectors'
    | '/recipes/$recipeId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/images/$'
    | '/recipes/edit/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/import'
    | '/weekly-menu'
    | '/api/chat'
    | '/'
    | '/admin/tags'
    | '/admin/vectors'
    | '/recipes/$recipeId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/images/$'
    | '/recipes/edit/$recipeId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/import'
    | '/_authed/weekly-menu'
    | '/api/chat'
    | '/_authed/'
    | '/_authed/admin/tags'
    | '/_authed/admin/vectors'
    | '/_authed/recipes/$recipeId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/images/$'
    | '/_authed/recipes/edit/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/weekly-menu': {
      id: '/_authed/weekly-menu'
      path: '/weekly-menu'
      fullPath: '/weekly-menu'
      preLoaderRoute: typeof AuthedWeeklyMenuRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/import': {
      id: '/_authed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthedImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recipes/$recipeId': {
      id: '/_authed/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthedRecipesRecipeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/vectors': {
      id: '/_authed/admin/vectors'
      path: '/admin/vectors'
      fullPath: '/admin/vectors'
      preLoaderRoute: typeof AuthedAdminVectorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tags': {
      id: '/_authed/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthedAdminTagsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/edit/$recipeId': {
      id: '/_authed/recipes/edit/$recipeId'
      path: '/recipes/edit/$recipeId'
      fullPath: '/recipes/edit/$recipeId'
      preLoaderRoute: typeof AuthedRecipesEditRecipeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedImportRoute: typeof AuthedImportRoute
  AuthedWeeklyMenuRoute: typeof AuthedWeeklyMenuRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminTagsRoute: typeof AuthedAdminTagsRoute
  AuthedAdminVectorsRoute: typeof AuthedAdminVectorsRoute
  AuthedRecipesRecipeIdRoute: typeof AuthedRecipesRecipeIdRoute
  AuthedRecipesEditRecipeIdRoute: typeof AuthedRecipesEditRecipeIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedImportRoute: AuthedImportRoute,
  AuthedWeeklyMenuRoute: AuthedWeeklyMenuRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminTagsRoute: AuthedAdminTagsRoute,
  AuthedAdminVectorsRoute: AuthedAdminVectorsRoute,
  AuthedRecipesRecipeIdRoute: AuthedRecipesRecipeIdRoute,
  AuthedRecipesEditRecipeIdRoute: AuthedRecipesEditRecipeIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
